### PR TITLE
Fix deployment issues on Mac

### LINKED ISSUE #152: deploy.sh does not work on Mac
Ran into some issues setting up local development:
 
* Explicitly specifying the executable paths (`/usr/bin/` or `/bin/` prefixes) doesn't always match my Mac's setup. For example, `realpath` is at `/bin/realpath` instead of `/usr/bin/realpath` on my computer. Not sure if the absolute paths were done for a specific reason (eg if you're worried about people with bizarre PATHs or aliases) but it seems easier to just use whatever executables are in the PATH.
* On top of that, while my Mac already had `realpath`, I think this might not be true for all Macs. Maybe it's worth rewriting using `pwd` instead?
* The flag lists can't be set as empty lists (`mod_feature_flags=()`) when, for example, DBH isn't installed. There should be other ways to define the list that work with that.

### PR DESCRIPTION
**Pull request by BenjaminTzudiker**
closes #152 

* Allows empty flags for testing w/o DBH
* Removes absolute path prefixes for basic commands like `mkdir`
* Replaces `realpath` with a more generic equivalent
* Adds a check to make sure the user updated the steam path
* Ignores Rider (seems like a common .NET capable IDE for Mac) project settings directory

### CODE REVIEW

**Comment by frederik-hoeft** [comment]
hey, thanks for your PR!

Yeah, I haven't really considered Mac, or BSD systems, TBH, so it's good that someone takes a look at those scripts 😅

I think there's another bash script for installing optional workshop dependencies into the dev environment, so we might need to take a look at that as well for consistency.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 1]
```diff
@@ -11,9 +11,9 @@ game_version="1.6"
 mod_feature_flags=( "ModBadHygiene" )
 
 # Resolve script directory (where this script lives)
-script_dir="$(/usr/bin/realpath "$(/usr/bin/dirname "${BASH_SOURCE[0]}")")"
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 # Resolve mod root (4 levels up from script directory)
-mod_root="$(/usr/bin/realpath "${script_dir}/../../../..")"
+mod_root="$(cd "${script_dir}/../../../.." && pwd)"
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: let's maybe tweak this to use the -P switch for pwd (if that exists on BSD/Mac) to get reliable symlink behavior for weird system setups, same on L14.

`script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"`

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 2]
```diff
@@ -27,10 +27,16 @@ log_message() {
 # Read the hostconfig file (located next to this script)
 log_message "Reading host configuration file..."
 steam_root="$(jq -r '.steam_root' "${script_dir}/hostconfig.json")"
-upload_dir="${steam_root}/steamapps/common/RimWorld/Mods/${project_name}"
+if [[ "$steam_root" == "G:/SteamLibrary" ]]
+then
+  echo "Error: You must update the 'steam_root' value in hostconfig.json."
+  exit 1
+fi
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: This will throw for anyone who is using `G:/SteamLibrary` as their legitimate steam library install location, e.g., on windows using mingw (i.e., me 🙃). I think it should be save to use a more clear sentinel value as the default  `$steam_root` value in the checked-in sample config, something which doesn't fall into the value space. Maybe `/path/to/your/steam-library`?

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 3]
```diff
@@ -27,10 +27,16 @@ log_message() {
...
+upload_dir="${steam_root}/steamapps/common/RimWorld/RimWorldMac.app/Mods/${project_name}"
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: I didn't consider the path being different on mac, but with this change it certainly breaks on Windows MinGW/WSL setups and likely on Linux as well. Does Mac have an easilily grep-able `uname -a` string we could look for to make this conditional?

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 4]
```diff
@@ -39,18 +45,18 @@ done
...
 if [[ -e "${upload_dir}" ]]; then
-  /bin/rm -rf -- "${upload_dir}"
+  rm -rf -- "${upload_dir}"
 fi
 
 # create new folder structure
-/bin/mkdir -p -- "${upload_dir}"
-/bin/mkdir -p -- "${upload_dir}/Source"
+mkdir -p "${upload_dir}"
+mkdir -p "${upload_dir}/Source"
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: `${upload_dir}` is user-controlled/system-specific and could be weird, so let's keep the `--`

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 5]
```diff
@@ -107,78 +113,78 @@ if [[ -d "${old_versions_dir}" ]]; then
...
 
-    tmpdir="$(/usr/bin/mktemp -d)"
+    tmpdir="$(mktemp -d)"
     tmpzip="${tmpdir}/${version_name}.zip"
     tmpextract="${tmpdir}/${version_name}_extract"
 
     # Download (curl preferred)
-    if command -v /usr/bin/curl >/dev/null 2>&1; then
-      /usr/bin/curl -fL --retry 3 --retry-delay 1 -o "${tmpzip}" "${download_link}"
+    if command -v /curl >/dev/null 2>&1; then
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: probably a typo: `/curl` likely (hopefully) won't ever exist in the fs root on most systems

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 6]
```diff
@@ -107,78 +113,78 @@ if [[ -d "${old_versions_dir}" ]]; then
     fi
 
     ref_file="${ref_files[0]}"
-    raw_version="$(/usr/bin/basename "${ref_file}")"
+    raw_version="$(basename "${ref_file}")"
     raw_version="${raw_version%.ref}"
 
     # Read link (trim common whitespace/newlines)
-    download_link="$(/usr/bin/sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//' "${ref_file}")"
+    download_link="$(sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//' "${ref_file}")"
```
Comment (frederik-hoeft) [inline Source/MoreInjuries/MoreInjuries/_build/deploy.sh:128]: for this and all other occurrences of `sed`, did you confirm that the intended behavior still works on Mac? Originally, this was written against GNU sed/grep/etc, and I know that at least some of the CLI options are different in the BSD implementation. I'm not too familiar with BSD though / haven't checked myself, therefore the question

**Review by frederik-hoeft — CHANGES_REQUESTED** [review]

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 2 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Huh, I didn't know that was a real steam install directory, haha.

I'll just make sure the directory exists for now, which is probably what I should have done from the start...

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 3 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Good idea, should have seen that coming. `uname -s` gives `Darwin` for Mac, so I'll just swap on that.

What kernel do you get on MinGW, just to double check?

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 4 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Done.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 5 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Oops, yes.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 6 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:128]: I didn't explicitly confirm, but the script seemed to work fine (at least on 1.6) and I didn't notice anything that looked like it wouldn't work.
* You're already using `-E`, which should work for both, instead of `-r`.
* Similarly, I see you're already using `[[:space:]]` instead of `\s`.
* Looks like `-e` works for both.

Not confident I'd be able to catch issues at a glance though, so I can check more thoroughly later if desired.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 1 above)
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Done.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 6 above)
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:128]: as long as it works, that's fine. developer tooling doesn't need to follow the same QA standards, we can iterate on it in the future if there turn out to be any issues

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 3 above)
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: `uname -s` on MinGW yields `MINGW64_NT-${Windows SemVer string}`

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 2 above)
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Yeah, that's probably good enough. I can fix the whole `G:/SteamLibrary` config leakage thing separately and use a more descriptive sample value

**Review by frederik-hoeft — APPROVED** [review]
LGTM, unless copilot finds anything we missed

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 7]
```diff
@@ -27,10 +27,23 @@ log_message() {
...
+  exit 1
+fi
+
+kernel_name="$(uname -s)"
+if [[ "$kernel_name" == "Darwin" ]]; then
+  # Mac install directory
+  upload_dir="${steam_root}/steamapps/common/RimWorld/RimWorldMac.app/Mods/${project_name}"
+else
+  upload_dir="${steam_root}/steamapps/common/RimWorld/Mods/${project_name}"
+fi
```
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:42]: `RimWorldMac.app` certainly exists (as briefly mentioned [here](https://rimworldwiki.com/wiki/Modding_Tutorials/First_Steps#Step_2:_Read_Other_Info_On_Modding)), but the wiki does indeed link to a different(?) mod location for Mac: https://rimworldwiki.com/wiki/Modding#Manual_Installation

@BenjaminTzudiker can you double-check that your install path is the default path, and how it relates to the documented `Library/Application Support/Steam/steamapps/common/RimWorld` from the docs?

Could also be a false positive by copilot or outdated MacOS docs in the RimWorld wiki, that's why I'm asking

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 8]
```diff
@@ -107,78 +120,78 @@ if [[ -d "${old_versions_dir}" ]]; then
...
+    raw_version="$(basename "${ref_file}")"
     raw_version="${raw_version%.ref}"
 
     # Read link (trim common whitespace/newlines)
-    download_link="$(/usr/bin/sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//' "${ref_file}")"
+    download_link="$(sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//' "${ref_file}")"
     [[ -n "${download_link}" ]] || continue
 
-    tmpdir="$(/usr/bin/mktemp -d)"
+    tmpdir="$(mktemp -d)"
```
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:131]: From the OpenBSD man pages (https://man.openbsd.org/mktemp), but not sure if this is the exact version used by MacOS.

> If no template is specified, a default value of tmp.XXXXXXXXXX is used and the -t flag is implied (see below).

@BenjaminTzudiker please double check whether `mktemp -d` succeeds without any additional args on Mac.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 9]
```diff
@@ -11,9 +11,9 @@ game_version="1.6"
 mod_feature_flags=( "ModBadHygiene" )
 
 # Resolve script directory (where this script lives)
-script_dir="$(/usr/bin/realpath "$(/usr/bin/dirname "${BASH_SOURCE[0]}")")"
+script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
```
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: the more you know

The logic seems to work though, in both cases: when invoked as an executable script using the shebang and when passed as an argument to bash directly

[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: actually, this fails if someone ever moves the script to the fs root and invokes it as `/deploy.sh`, then we'd get `cd -- ""` (not sure why anyone would do that though).

So we either need to add another check for the empty string:

```bash

script_source="${BASH_SOURCE[0]}"
script_dirname="${script_source%/*}"

if [[ "$script_dirname" == "$script_source" ]]; then
  script_dirname="."
elif [[ -z "$script_dirname" ]]; then
  script_dirname="/"
fi

script_dir="$(cd -- "$script_dirname" && pwd -P)"
```

or we just drop the `--` arg from `dirname` and if someone decides to name their directories in a weird option-like way, then tough luck for them.

I honestly favor the second option here, so `script_dir="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"`

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 10]
```diff
@@ -27,10 +27,23 @@ log_message() {
...
+if [[ "$kernel_name" == "Darwin" ]]; then
+  # Mac install directory
+  upload_dir="${steam_root}/steamapps/common/RimWorld/RimWorldMac.app/Mods/${project_name}"
+else
+  upload_dir="${steam_root}/steamapps/common/RimWorld/Mods/${project_name}"
+fi
 
 # Build mod flag properties
 mod_flag_properties=()
+(( ${#mod_feature_flags[@]} )) && \
```
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:47]: LLM hallucinations, this is valid syntax.

Although iterating the empty array indeed is a noop. @BenjaminTzudiker is there a specific reason for the emptiness check here?

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh [hunk 11]
```diff
@@ -39,18 +52,18 @@ done
 log_message "Building and publishing ${project_name} v${game_version}..."
 dotnet clean "${project_path}"
 dotnet restore "${project_path}" --no-cache
-dotnet build "${project_path}" -c "${configuration}" "${mod_flag_properties[@]}"
-dotnet publish "${project_path}" -c "${configuration}" -p:PublishProfile="${configuration}" "${mod_flag_properties[@]}"
+dotnet build "${project_path}" -c "${configuration}" "${mod_flag_properties[@]:-}"
+dotnet publish "${project_path}" -c "${configuration}" -p:PublishProfile="${configuration}" "${mod_flag_properties[@]:-}"
```
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: dotnet build doesn't care about empty args, but we can still simplify this

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 9 above)
[the remark this answers is not in the document]
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Sounds good. I've never heard of that weird distinction for -- on macOS... The more you know indeed.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 10 above)
[the remark this answers is not in the document]
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:47]: Without that line, I was getting `line 49: mod_feature_flags[@]: unbound variable`. `:-` also doesn't work here since it adds one flag with an empty name.

Looking a bit deeper, apparently [this is supposed to work without that line in newer versions of bash](https://cgit.git.savannah.gnu.org/cgit/bash.git/tree/CHANGES?id=3ba697465bc74fab513a26dea700cc82e9f4724e#n878)?

> Using ${a[@]} or ${a[*]} with an array without any assigned elements when the nounset option is enabled no longer throws an unbound variable error.

Apparently I'm still on bash 3.2 - I have no idea why, I'm using a 2021 Mac. If it works fine for up-to-date versions, do you mind if it stays to help people like me with oddly out of date bash versions?

Edit:

Apparently this might have to do with [IP laws](https://news.ycombinator.com/item?id=38132066):

> It's because Bash 3.2 is the last version licensed as GPLv2. Bash 4.0 and later changed license to GPLv3.
> 
> Apple decided it's not safe for them to ship any software with GPLv3 with macOS, because of stronger legal conditions in GPLv3. This is also the reason they stopped updating Samba.
> 
> They changed the default shell to Zsh long ago. The old Bash is kept around, so that users who want to stick with Bash can still use it as their shell, and so that existing scripts for macOS (for example in installers) continue to work. If nobody cared about Bash, I expect they would have dropped it from macOS when switching to Zsh, rather than keeping the old version.
> 
> So from a certain point of view, Bash 3.2 is the most recent version they can ship.

So unless Mac devs need to update their bash or the script switches to use zsh (assuming that works like newer versions of bash, which is something I know nothing about), it seems like this is a real compatibility issue.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 8 above)
[the remark this answers is not in the document]
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:131]:
```
MacBook-Pro-39:rimworld-more-injuries benjamintzudiker$ mktemp -d
/var/folders/2g/3tl5yqnx7n7cp56brrt6dt2h0000gn/T/tmp.eH8HGJAzm0
MacBook-Pro-39:rimworld-more-injuries benjamintzudiker$ ls /var/folders/2g/3tl5yqnx7n7cp56brrt6dt2h0000gn/T
...
tmp.eH8HGJAzm0
...
```

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 7 above)
[the remark this answers is not in the document]
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:42]: I think that path is incomplete (it also doesn't list the `/Mods` part unlike the other OSes). This other page lists the app folder correctly as part of the path: https://rimworldwiki.com/wiki/Modding_Tutorials/Mod_Folder_Structure

I'm pretty sure I never modified anything on my end. I see some [other people](https://www.reddit.com/r/RimWorld/comments/yvggf0/where_is_the_mods_folder_for_mac/) also saying `Mods` is inside the application (though that person messes up the capitalization and does not see the `.app` suffix since macOS hides that by default), so I think this is the correct location.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 11 above)
[the remark this answers is not in the document]
Comment (BenjaminTzudiker) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh]: Looks like the same old version of bash issue on my end.

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 7 above)
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:42]: Gotcha, the wiki documentation is just inconsistent then

File: Source/MoreInjuries/MoreInjuries/_build/deploy.sh (hunk 10 above)
[the remark this answers is not in the document]
Comment (frederik-hoeft) [reply Source/MoreInjuries/MoreInjuries/_build/deploy.sh:47]: interesting, I wasn't aware of that :0

but in that case it's fine, old bash versions require it and on newer versions it's just a noop
